# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    build: ./postgres/
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
